[package]
name = "odysseus-identity-manager"
version = "0.1.0"
authors = ["simone.romano <simone.romano@noku.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Actix web redis session
actix-redis = "0.9.2"
# Actix web sessions
actix-session = "0.4.1"
# HTTP Server
actix-web = "3.3.2"
# Password hashing
argon2 = "0.2.0"
# Configuration helper
config = "0.11.0"
# Basic logging
log = "0.4.14"
# File logging
log4rs = "1.0.0"
# Lazy static evaluation
once_cell = "1.7.2"
# OpenAPI documentation
paperclip = { git = "https://github.com/wafflespeanut/paperclip.git", rev = "20ec2e954dfb15613807130105a41e8f4b91066e", features = ["actix3-nightly", "actix-session"] }
# Cryptographically secure random
rand = "0.8.3"
# Serialize and deserialize
serde = "1.0.126"
# JSON ser/de
serde_json = "1.0.64"
# Error derive
thiserror = "1.0.25"
# MongoDB ODM
wither = "0.9.0"
