version: "3.6"

services:
  app:
    build: 
      context: .
      dockerfile: ./.docker/odysseus-identity-manager-server.dockerfile
    ports: 
      - 8000:80

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports: 
      - 6379:6379

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  swagger-ui:
    image: swaggerapi/swagger-ui
    restart: unless-stopped
    ports:
      - 8082:8080
    environment:
      SWAGGER_JSON_URL: http://localhost:8000/openapi/docs
